login: &login
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 20
  username: root
  password:

development:
  <<: *login
  database: bookingsystem_development
test: &test
  <<: *login
  database: bookingsystem_test

production:
  <<: *login
  database: bookingsystem_production
  username: root
  password: vol5ada5mysql

staging:
  <<: *login
  database: bookingsystem_staging
  username: root
  password: vol5ada5mysql

cucumber:
  <<: *test